name: Check OneBot Plugins

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests toml

      - name: Run OneBot checker script
        run: |
          python main.py

      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: onebot_plugins_result
          path: onebot_plugins.json
